[detectors]
exclude = []
exclude_paths = [
    "node_modules",
    "venv",
    "lib",
]

[testing]
cmd = "hardhat"

[testing.anvil]
cmd_args = "--prune-history 100 --steps-tracing --silent"

[testing.ganache]
cmd_args = "-k istanbul -q"

[testing.hardhat]
cmd_args = ""

[compiler.solc]
include_paths = [
    "node_modules",
]
exclude_paths = [
    "node_modules",
    "venv",
    "lib",
    "audits",
]

[compiler.solc.optimizer]
enabled = true
runs = 200
