[detectors]
exclude = []
ignore_paths = [ "node_modules", ".woke-build", "venv", "lib",]

[testing]
cmd = "hardhat"

[testing.anvil]
cmd_args = "--prune-history 100 --steps-tracing --silent"

[testing.ganache]
cmd_args = "-k istanbul -q"

[testing.hardhat]
cmd_args = ""

[compiler.solc]
ignore_paths = [ "node_modules", ".woke-build", "venv", "lib", "audits",]
include_paths = [ "node_modules",]

[compiler.solc.optimizer]
enabled = true
runs = 200
